version: "3"
name: sample-rails-project
services:
  db:
    image: postgres:14.5-alpine
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sample_rails_project_production
    ports:
      - "9000:5432"
  web:
    build:
      dockerfile: Dockerfile.test
    command: "./bin/rails server"
    environment:
      - SAMPLE_RAILS_PROJECT_DATABASE_HOST=db
      - SAMPLE_RAILS_PROJECT_DATABASE_USERNAME=postgres
      - SAMPLE_RAILS_PROJECT_DATABASE_PASSWORD=1234
      - SAMPLE_RAILS_PROJECT_DATABASE_PORT=5432
    depends_on:
      - db
    ports:
      - "3000:3000"
