version: "3"
name: sample-rails-project
services:
  db:
    image: postgres:14.5-alpine
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sample_rails_project_production

  web:
    image: vancego/sample-web:latest
    command: "./bin/rails server"
    environment:
      - SAMPLE_RAILS_PROJECT_DATABASE_HOST=db
      - SAMPLE_RAILS_PROJECT_DATABASE_USERNAME=postgres
      - SAMPLE_RAILS_PROJECT_DATABASE_PASSWORD=1234
      - SAMPLE_RAILS_PROJECT_DATABASE_PORT=5432
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: on-failure
