default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["SAMPLE_RAILS_PROJECT_DATABASE_HOST"] %>
  port: <%= ENV["SAMPLE_RAILS_PROJECT_DATABASE_PORT"] %>
  username: <%= ENV["SAMPLE_RAILS_PROJECT_DATABASE_USERNAME"] %>
  password: <%= ENV["SAMPLE_RAILS_PROJECT_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: sample_rails_project_development

test:
  <<: *default
  database: sample_rails_project_test

production:
  <<: *default
  database: sample_rails_project_production
